# Generated by Django 5.2.3 on 2025-06-27 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0008_alter_upvote_report_alter_upvote_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam or fake'), ('offensive', 'Offensive content'), ('duplicate', 'Duplicate report'), ('other', 'Other')], max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('action_taken', models.CharField(choices=[('report_removed', 'Report removed'), ('user_warned', 'User warned'), ('no_action', 'No action')], default='no_action', max_length=255)),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_flags', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='reports.report')),
            ],
            options={
                'verbose_name': 'flag',
                'verbose_name_plural': 'flags',
            },
        ),
    ]
