# Generated by Django 5.2.3 on 2025-06-27 06:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flags', '0001_initial'),
        ('reports', '0008_alter_upvote_report_alter_upvote_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='flag',
            constraint=models.UniqueConstraint(models.F('report'), models.F('flagged_by'), name='unique_report_flagged_by'),
        ),
    ]
