[project]
name = "ai-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.116.0",
    "numpy>=2.3.1",
    "pandas>=2.3.1",
    "ruff>=0.12.2",
    "scikit-learn>=1.7.0",
]
