# Generated by Django 5.2.3 on 2025-06-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'contact us', 'verbose_name_plural': 'contact us'},
        ),
    ]
