# Generated by Django 5.2.3 on 2025-06-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_contactus_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='subject',
            field=models.CharField(choices=[('general_inquiry', 'General Inquiry'), ('technical_support', 'Technical Support'), ('partnership', 'Partnership'), ('feedback', 'Feedback'), ('press', 'Press')], default='general_inquiry', max_length=50),
        ),
    ]
