# Generated by Django 5.2.3 on 2025-06-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='address',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
