# Generated by Django 5.2.3 on 2025-06-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_report_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, default='default_images/no_image_available.jpg', null=True, upload_to='report_images/'),
        ),
    ]
