# Generated by Django 5.2.3 on 2025-06-20 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_at'], 'verbose_name': 'report', 'verbose_name_plural': 'reports'},
        ),
    ]
