# Generated by Django 5.2.3 on 2025-06-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_report_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=255),
        ),
        migrations.AddField(
            model_name='category',
            name='name_nepali',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
